Beer-Quest/Controllers/CheersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Beer_Quest.Data;
using Beer_Quest.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Beer_Quest.Models.ViewModels;

namespace Beer_Quest.Controllers
{
    public class CheersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CheersController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Cheers
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var cheer = await _context.Cheer.Include(c=> c.Brewery).Where(c => c.UserId == user.Id).Select(c => new BreweryCheerCountViewModel 
            { 
                Name = c.Brewery.Name,
                Id = c.Brewery.Id,
                Address = c.Brewery.Address,
                City = c.Brewery.City,
                ZipCode = c.Brewery.ZipCode,
                Phone = c.Brewery.Phone,
                CheersCount = c.Brewery.Cheers.Count(),
                CommentCount = c.Brewery.Comments.Count(),
                ImagePath = c.Brewery.ImagePath

            }).ToListAsync();
            return View(cheer);
        }

        // GET: Cheers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cheer = await _context.Cheer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cheer == null)
            {
                return NotFound();
            }

            return View(cheer);
        }

        // POST: Cheers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int breweryId)
        {
            var user = await GetCurrentUserAsync();
            var cheers = await _context.Cheer.Where(c => c.UserId == user.Id && c.BreweryId == breweryId).FirstOrDefaultAsync();
            var cheer = new Cheer();

            if(user == null)
            {

            }

            if (cheers != null)
            {
                return RedirectToAction("Index", "Breweries");
            }
            else if(ModelState.IsValid && cheers == null)
            {
                cheer.BreweryId = breweryId;
                cheer.UserId = user.Id;
                _context.Add(cheer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Breweries");
            }
            return View();
        }

        // GET: Cheers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cheer = await _context.Cheer.FindAsync(id);
            if (cheer == null)
            {
                return NotFound();
            }
            return View(cheer);
        }

        // POST: Cheers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,BreweryId")] Cheer cheer)
        {
            if (id != cheer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cheer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CheerExists(cheer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cheer);
        }

        // GET: Cheers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cheer = await _context.Cheer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cheer == null)
            {
                return NotFound();
            }

            return View(cheer);
        }

        // POST: Cheers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cheer = await _context.Cheer.FindAsync(id);
            _context.Cheer.Remove(cheer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CheerExists(int id)
        {
            return _context.Cheer.Any(e => e.Id == id);
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
    }
}

Beer-Quest/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Beer_Quest.Data;
using Beer_Quest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Beer_Quest.Models.ViewModels;

namespace Beer_Quest.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CommentsController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Comments
        public async Task<IActionResult> Index(int breweryId)
        {
            var comments = await _context.Comment.Include(c => c.User).Where(c => c.BreweryId == breweryId).ToListAsync();
            var brewery = _context.Brewery.Include(b=> b.Cheers).FirstOrDefault(b => b.Id == breweryId);
            ViewBag.BreweryId = breweryId;
            ViewBag.Brewery = brewery;
            ViewBag.BreweryImage = brewery.ImagePath;
            ViewBag.CheersCount = brewery.Cheers.Count();
            if (comments.Count() > 0)
            {
                var viewModel = new BreweryCommentViewModel
                {
                    Brewery = brewery,
                    Comments = comments
                };
                return View(viewModel);
            }
            else
            {
                var viewModel = new BreweryCommentViewModel
                {
                    Brewery = brewery
                };
                return View("NoComments");
            }
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        [Authorize]

        // GET: Comments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int breweryId, BreweryCommentViewModel viewModel)
        {
            var user = await GetCurrentUserAsync();
            var comment = new Comment
            {
                BreweryId = breweryId,
                Text = viewModel.UserComment,
                UserId = user.Id
            };
            if (ModelState.IsValid)
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { breweryId });
            }
            return View(comment);
        }

        // GET: Comments/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Text,BreweryId,UserId")] Comment comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comment.FindAsync(id);
            _context.Comment.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
            return _context.Comment.Any(e => e.Id == id);
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
    }
}

Beer-Quest/Controllers/DrinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Beer_Quest.Data;
using Beer_Quest.Models;

namespace Beer_Quest.Controllers
{
    public class DrinksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DrinksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Drinks
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Drink.Include(d => d.Brewery).Include(d => d.DrinkType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Drinks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drink
                .Include(d => d.Brewery)
                .Include(d => d.DrinkType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (drink == null)
            {
                return NotFound();
            }

            return View(drink);
        }

        // GET: Drinks/Create
        public IActionResult Create(int breweryId)
        {
            ViewBag.breweryId = breweryId;
            ViewData["DrinkTypeId"] = new SelectList(_context.DrinkType, "Id", "Name");
            return View();
        }

        // POST: Drinks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,AlcoholPercent,DrinkTypeId,BreweryId,HouseFav")] Drink drink)
        {
            if (ModelState.IsValid)
            {
                _context.Add(drink);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Breweries", new { id = drink.BreweryId});
            }
            ViewData["BreweryId"] = new SelectList(_context.Brewery, "Id", "Id", drink.BreweryId);
            ViewData["DrinkTypeId"] = new SelectList(_context.DrinkType, "Id", "Id", drink.DrinkTypeId);
            return View(drink);
        }

        // GET: Drinks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drink.FindAsync(id);
            if (drink == null)
            {
                return NotFound();
            }
            ViewData["BreweryId"] = new SelectList(_context.Brewery, "Id", "Id", drink.BreweryId);
            ViewData["DrinkTypeId"] = new SelectList(_context.DrinkType, "Id", "Id", drink.DrinkTypeId);
            return View(drink);
        }

        // POST: Drinks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,AlcoholPercent,DrinkTypeId,BreweryId,HouseFav")] Drink drink)
        {
            if (id != drink.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(drink);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DrinkExists(drink.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreweryId"] = new SelectList(_context.Brewery, "Id", "Id", drink.BreweryId);
            ViewData["DrinkTypeId"] = new SelectList(_context.DrinkType, "Id", "Id", drink.DrinkTypeId);
            return View(drink);
        }

        // GET: Drinks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drink = await _context.Drink
                .Include(d => d.Brewery)
                .Include(d => d.DrinkType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (drink == null)
            {
                return NotFound();
            }

            return View(drink);
        }

        // POST: Drinks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var drink = await _context.Drink.FindAsync(id);
            _context.Drink.Remove(drink);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DrinkExists(int id)
        {
            return _context.Drink.Any(e => e.Id == id);
        }
    }
}

Beer-Quest/Views/Breweries/Create.cshtml
@model Beer_Quest.Models.Brewery

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Brewery</h4>
<div class="card-divs">
    <div class="card" style="width: 50%;">
        <h3 class="card-header card-header-footer">Create Brewery</h3>
        <div>
            <div class="" style="width: 70%; margin-left: 20px;">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ZipCode" class="control-label"></label>
                        <input asp-for="ZipCode" class="form-control" />
                        <span asp-validation-for="ZipCode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="File" class="control-label"></label>
                        <input name="file" type="file" class="form-control" />
                        <span asp-validation-for="File" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>

            <div class="card-body card-header-footer">
                <a asp-action="Index" asp-controller="Breweries">Back To List</a>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Beer-Quest/Views/Breweries/Delete.cshtml
@model Beer_Quest.Models.Brewery

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brewery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheersCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheersCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Beer-Quest/Views/Breweries/Details.cshtml
@model Beer_Quest.Models.ViewModels.BreweryCheerCountViewModel

@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Details";
}

@{var user = await UserManager.GetUserAsync(User);}

<div class="card-divs">
    <div class="card" style="width: 50%;">
        <h3 class="card-header card-header-footer">@Html.DisplayFor(model => model.Name)</h3>
        <img class="img-thumbnail" style="height: 125px; width: 150px; padding:0px; margin:5px;" src="@Url.Content("~/images/" + Model.ImagePath)" alt="" />
        <div style="width:16%;">
            @if (user != null)
            {
                <form class="cheers-button-form" style="padding:5px;" asp-action="Create" asp-controller="Cheers" asp-route-breweryId="@Model.Id">
                    <button type="submit" class=" btn btn-outline-info" style="background-color: #034381 !important;"><img class="image-button" src="~/Images/CheersButton.png" style="height:25px; width:25px;" /></button>
                    <p style="color: ghostwhite;">@Html.DisplayFor(model => model.CheersCount)</p>

                </form>
            }
            else
            {
                <p class="cheers-button-form" style="color: ghostwhite;">
                    Cheers:a
                    @Html.DisplayFor(model => model.CheersCount)
                </p>
            }
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item card-items">
                <p class="font-weight-bold">Address: </p>
                @Html.DisplayFor(model => model.Address)
            </li>
            <li class="list-group-item card-items">
                <p class="font-weight-bold">City: </p>
                @Html.DisplayFor(model => model.City)
            </li>
            <li class="list-group-item card-items">
                <p class="font-weight-bold">Phone: </p>
                @Html.DisplayFor(model => model.Phone)
            </li>
            <li class="list-group-item card-items">
                <p class="font-weight-bold">Drinks:</p>
                @if (Model.Drinks.Count() > 0)
                {
                    @foreach (var item in Model.Drinks)
                    {
                        <p>@item.Name (@item.AlcoholPercent% alc/vol)</p>
                    }
                }
                else
                {
                    <p>Sorry, no drinks are posted for this brewery yet.. :(</p>
                }
                @if (user != null)
                {
                    if (user.UserTypeId == 1 || user.UserTypeId == 2)
                    {
                        <a class=" btn btns" style="background-color: #033E76; border-radius: 15px; color: ghostwhite;" asp-action="Create" asp-controller="Drinks" asp-route-breweryId="@Model.Id">Add Drink</a>
                    }
                }
            </li>
            <li class="list-group-item card-items">
                <p style="color: ghostwhite;">@Model.CommentCount </p>
                <a asp-action="Index" asp-controller="Comments" asp-route-breweryId="@Model.Id">View Comments</a>
            </li>
        </ul>
        <div class="card-body card-header-footer">
            @if (user != null)
            {
                @if (user.UserTypeId == 2 && user.Id == Model.UserId)
                {
                    <a asp-action="Edit" asp-route-id="@Model.Id">Edit Brewery |</a>
                }
                else if (user.UserTypeId == 1)
                {
                    <a asp-action="Edit" asp-route-id="@Model.Id">Edit Brewery |</a>
                    <a asp-action="Delete" asp-route-id="@Model.Id">Delete |</a>
                }
            }
            <a asp-action="Index"s>Back To List</a>
        </div>
    </div>
</div>

Beer-Quest/Views/Breweries/Index.cshtml
@model IEnumerable<Beer_Quest.Models.ViewModels.BreweryCheerCountViewModel>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{var user = await UserManager.GetUserAsync(User);}


@{
    ViewData["Title"] = "Index";
}


@if (user != null)
{
    if (user.UserTypeId == 1)
    {
        <div class="create-brewery-wrapper">
            <div class="create-brewery-button">
                <p class="text-center">
                    <a asp-action="Create">Create New Brewery</a>
                </p>
            </div>
        </div>
    }
}

@foreach (var item in Model)
{
    <div class="card-divs">
        <div class="card" style="width: 50%;">
            <h3 class="card-header card-header-footer">@Html.DisplayFor(modelItem => item.Name)</h3>
            <img class="img-thumbnail" style="height: 125px; width: 150px; padding:0px; margin:5px;" src="@Url.Content("~/images/" + item.ImagePath)" alt="" />
            <div style="width:16%;">
                @if (user != null)
                {
                    <form class="cheers-button-form" style="padding:5px;" asp-action="Create" asp-controller="Cheers" asp-route-breweryId="@item.Id">
                        <button type="submit" class=" btn btn-outline-info" style="background-color: #034381 !important;"><img class="image-button" src="~/Images/CheersButton.png" style="height:25px; width:25px;" /></button>
                        <p style="color: ghostwhite;">@Html.DisplayFor(modelItem => item.CheersCount)</p>
                    </form>
                }
                else
                {
                    <p class="cheers-button-form">
                        Cheers:
                        @Html.DisplayFor(modelItem => item.CheersCount)
                    </p>
                }
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item card-items">
                    <p class="font-weight-bold">City: </p>
                    @Html.DisplayFor(modelItem => item.City)
                </li>
                <li class="list-group-item card-items">
                    <p class="font-weight-bold">Phone: </p>
                    @Html.DisplayFor(modelItem => item.Phone)
                </li>
            </ul>
            <div class="card-body card-header-footer">
                @if (user != null)
                {
                    @if (user.UserTypeId == 2 && user.Id == item.UserId)
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit Brewery |</a>
                    }
                    else if(user.UserTypeId == 1)
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit Brewery |</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete |</a>
                    }
                }
                <a asp-action="Details" asp-route-id="@item.Id">View Brewery</a>
            </div>
        </div>
    </div>
}

@*<table class="table table-striped">
        <tbody>
            @foreach (var item in Model)
            {
                <card>
                    <tr>
                        <card>

                            <td>
                                <img class="img-thumbnail" style="max-width: 150px;" src="@Url.Content("~/images/" + item.ImagePath)" alt="" />
                                @if (user != null)
                                {
                                    <form asp-action="Create" asp-controller="Cheers" asp-route-breweryId="@item.Id">
                                        <button type="submit" class="image-button"><img class="image-button" src="~/Images/CheersButton.png" height="25px" width="25px" /></button>
                                        @Html.DisplayFor(modelItem => item.CheersCount)
                                    </form>
                                }
                                else
                                {
                                    <p>
                                        Cheers:
                                        @Html.DisplayFor(modelItem => item.CheersCount)
                                    </p>
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.City)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Phone)
                            </td>
                            <td>
                                @if (user != null)
                                {
                                    @if (user.UserTypeId == 1 || user.UserTypeId == 2 && user.Id == item.UserId)
                                    {
                                        <a asp-action="Edit" asp-route-id="@item.Id">Edit Brewery |</a>
                                    }
                                }
                                <a asp-action="Details" asp-route-id="@item.Id">View Brewery</a>
                                < asp-action="Delete" asp-route-id="@item.Id">Delete</>
                            </td>
                        </card>
                    </tr>
                </card>
            }
        </tbody>
    </table>*@